[project]
name = "rag-legislation-ia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "dotenv>=0.9.9",
    "fastapi>=0.136.1",
    "jupyter>=1.1.1",
    "pypdf>=6.9.2",
    "uvicorn>=0.46.0",
]
